import { Platform } from 'react-native';
import * as Notifications from 'expo-notifications';
import * as SecureStore from 'expo-secure-store';
import Constants from 'expo-constants';
import { rideOnApi } from './api';
const PUSH_TOKEN_KEY='rideon_push_token';
Notifications.setNotificationHandler({handleNotification:async()=>({shouldShowBanner:true,shouldShowList:true,shouldPlaySound:true,shouldSetBadge:true})});
export async function configureNotificationChannel(){if(Platform.OS!=='android')return;await Notifications.setNotificationChannelAsync('rideon-transactional',{name:'RideOn updates',importance:Notifications.AndroidImportance.HIGH,vibrationPattern:[0,250,150,250],lockscreenVisibility:Notifications.AndroidNotificationVisibility.PUBLIC});}
export async function registerForPushNotifications(){await configureNotificationChannel();const permissions=await Notifications.getPermissionsAsync();let status=permissions.status;if(status!=='granted'){const requested=await Notifications.requestPermissionsAsync({ios:{allowAlert:true,allowBadge:true,allowSound:true}});status=requested.status;}if(status!=='granted')return {enabled:false,reason:status};const projectId=Constants.expoConfig?.extra?.eas?.projectId||Constants.easConfig?.projectId;const tokenResponse=await Notifications.getExpoPushTokenAsync(projectId?{projectId}:undefined);const token=tokenResponse?.data;if(!token)throw new Error('RideOn could not obtain a push notification token.');await rideOnApi.registerPushToken(token,Platform.OS,Constants.deviceName||null);try{await SecureStore.setItemAsync(PUSH_TOKEN_KEY,token);}catch{}return {enabled:true,token};}
export async function unregisterPushNotifications(){try{const token=await SecureStore.getItemAsync(PUSH_TOKEN_KEY);if(token)await rideOnApi.unregisterPushToken(token);await SecureStore.deleteItemAsync(PUSH_TOKEN_KEY);}catch{}}
export function subscribeToNotificationResponses(handler){const received=Notifications.addNotificationReceivedListener(notification=>handler?.({kind:'received',notification}));const response=Notifications.addNotificationResponseReceivedListener(response=>handler?.({kind:'response',notification:response.notification,data:response.notification.request.content.data||{}}));Notifications.getLastNotificationResponseAsync().then(last=>{if(last)handler?.({kind:'response',notification:last.notification,data:last.notification.request.content.data||{}});}).catch(()=>{});return()=>{received.remove();response.remove();};}