import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {rideOnApi} from '../services/api';
import {registerForPushNotifications} from '../services/notifications';
const C={ink:'#17202D',muted:'#78818E',orange:'#E85D35',bg:'#F6F7F9',white:'#FFFFFF',line:'#E8EAF0',green:'#258565'};
function timeLabel(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const diff=Math.max(0,Date.now()-date.getTime());if(diff<60000)return 'Just now';if(diff<3600000)return Math.floor(diff/60000)+'m ago';if(diff<86400000)return Math.floor(diff/3600000)+'h ago';return date.toLocaleDateString('en-IN',{day:'numeric',month:'short'});}
export default function NotificationCenter({onBack,onOpenNotification}){
 const [items,setItems]=useState([]),[unread,setUnread]=useState(0),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[loadingMore,setLoadingMore]=useState(false),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[error,setError]=useState(''),[pushState,setPushState]=useState('unknown');
 const load=useCallback(async(reset=true)=>{if(reset)setLoading(true);else setLoadingMore(true);setError('');try{const nextOffset=reset?0:offset;const [list,count]=await Promise.all([rideOnApi.listNotifications({limit:20,offset:nextOffset}),rideOnApi.getNotificationUnreadCount()]);const next=list?.notifications||[];setItems(prev=>reset?next:[...prev,...next]);setUnread(Number(count?.count||0));setOffset(nextOffset+next.length);setHasMore(Boolean(list?.pagination?.hasMore));}catch{setError('We could not load notifications right now. Please retry.');}finally{setLoading(false);setRefreshing(false);setLoadingMore(false);}},[offset]);
 useEffect(()=>{load(true);},[]);
 const markRead=async item=>{if(!item.readAt){setItems(prev=>prev.map(x=>x.id===item.id?{...x,readAt:new Date().toISOString()}:x));setUnread(v=>Math.max(0,v-1));await rideOnApi.markNotificationRead(item.id).catch(()=>{});}onOpenNotification?.(item);};
 const enablePush=async()=>{setPushState('loading');try{const result=await registerForPushNotifications();setPushState(result.enabled?'enabled':'denied');}catch{setPushState('error');}};
 if(loading)return <View style={s.center}><ActivityIndicator color={C.orange}/><Text style={s.muted}>Loading notifications…</Text></View>;
 return <View style={{flex:1,backgroundColor:C.bg}}><View style={s.header}><TouchableOpacity onPress={onBack}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Notifications</Text><Text style={s.muted}>{unread?unread+' unread':'All caught up'}</Text></View><TouchableOpacity onPress={async()=>{await rideOnApi.markAllNotificationsRead().catch(()=>{});setItems(x=>x.map(n=>({...n,readAt:n.readAt||new Date().toISOString()})));setUnread(0);}}><Text style={s.link}>Read all</Text></TouchableOpacity></View>
 <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}}/>} onScroll={({nativeEvent})=>{const {layoutMeasurement,contentOffset,contentSize}=nativeEvent;if(layoutMeasurement.height+contentOffset.y>=contentSize.height-120&&hasMore&&!loadingMore)load(false)}} scrollEventThrottle={250}>
 <View style={s.pushCard}><View style={{flex:1}}><Text style={s.cardTitle}>Stay updated</Text><Text style={s.muted}>Enable notifications for booking, payment, delivery and support updates.</Text></View><TouchableOpacity style={s.pushButton} onPress={enablePush} disabled={pushState==='loading'}><Text style={s.pushButtonText}>{pushState==='enabled'?'Enabled':pushState==='loading'?'Enabling…':pushState==='denied'?'Enable in Settings':'Enable'}</Text></TouchableOpacity></View>
 {error?<View style={s.error}><Text style={s.errorText}>{error}</Text><TouchableOpacity onPress={()=>load(true)}><Text style={s.link}>Retry</Text></TouchableOpacity></View>:null}
 {!items.length?<View style={s.empty}><Text style={s.emptyIcon}>♢</Text><Text style={s.cardTitle}>No notifications yet</Text><Text style={s.muted}>Important RideOn updates will appear here.</Text></View>:items.map(item=><TouchableOpacity key={item.id} onPress={()=>markRead(item)} style={[s.item,!item.readAt&&s.unread]}><View style={s.dot}>{!item.readAt&&<View style={s.dotOn}/>}</View><View style={{flex:1}}><View style={s.row}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.time}>{timeLabel(item.createdAt)}</Text></View><Text style={s.body}>{item.body}</Text>{item.bookingId&&<Text style={s.reference}>Booking {item.bookingId.slice(0,8)}…</Text>}{item.ticketId&&<Text style={s.reference}>Support ticket {item.ticketId.slice(0,8)}…</Text>}</View></TouchableOpacity>)}
 {loadingMore&&<ActivityIndicator color={C.orange} style={{margin:16}}/>}</ScrollView></View>;
}
const s=StyleSheet.create({header:{minHeight:62,paddingHorizontal:18,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line,backgroundColor:C.white},back:{fontSize:36,color:C.ink,width:42},title:{fontSize:18,fontWeight:'900',color:C.ink},muted:{fontSize:11,color:C.muted,lineHeight:17},link:{fontSize:12,fontWeight:'900',color:C.orange},content:{padding:16,paddingBottom:40},pushCard:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#FFF4EF',borderRadius:17,padding:15,marginBottom:12,borderWidth:1,borderColor:'#F4D9D0'},cardTitle:{fontSize:14,fontWeight:'900',color:C.ink},pushButton:{backgroundColor:C.orange,borderRadius:12,paddingHorizontal:13,paddingVertical:10},pushButtonText:{fontSize:11,fontWeight:'900',color:C.white},item:{flexDirection:'row',gap:12,backgroundColor:C.white,borderRadius:17,padding:15,marginBottom:10,borderWidth:1,borderColor:C.line},unread:{borderColor:'#F4C8BB',backgroundColor:'#FFFBF9'},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#DCE1E7',marginTop:5,alignItems:'center',justifyContent:'center'},dotOn:{width:9,height:9,borderRadius:5,backgroundColor:C.orange},row:{flexDirection:'row',justifyContent:'space-between',gap:10},itemTitle:{flex:1,fontSize:13,fontWeight:'900',color:C.ink},time:{fontSize:9,color:C.muted},body:{fontSize:12,color:C.muted,lineHeight:18,marginTop:5},reference:{fontSize:10,color:C.green,fontWeight:'800',marginTop:7},empty:{backgroundColor:C.white,borderRadius:20,padding:24,alignItems:'center',marginTop:20,borderWidth:1,borderColor:C.line},emptyIcon:{fontSize:36,color:C.orange},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10,backgroundColor:C.bg},error:{padding:12,borderRadius:12,backgroundColor:'#FFF0F0',marginBottom:12},errorText:{fontSize:12,color:'#B23B3B',fontWeight:'700'}});