import React from 'react';
import { Image, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
const C={ink:'#17202D',muted:'#78818E',orange:'#E85D35',line:'#E8EAF0',white:'#FFFFFF',green:'#258565'};
const money=value=>`₹${Number(value||0).toLocaleString('en-IN')}`;
export default function BookingConfirmation({booking,vehicle,onTrips,onExplore}){
 const pricing=booking?.pricing||{}, paid=String(booking?.paymentStatus||'').toLowerCase()==='paid';
 const image=[...(Array.isArray(vehicle?.images)?vehicle.images:[]),vehicle?.imageUrl,vehicle?.photoUrl].find(v=>typeof v==='string'&&/^https?:\/\//i.test(v));
 const vendor=vehicle?.vendorName||booking?.vehicle?.vendorName||booking?.vehicle?.vendor?.name||booking?.vehicle?.ownerName;
 return <View style={styles.page}><View style={[styles.icon,paid?styles.iconSuccess:styles.iconPending]}><Text style={styles.iconText}>{paid?'✓':'i'}</Text></View><Text style={styles.title}>{paid?'Booking Confirmed':'Payment verification pending'}</Text><Text style={styles.sub}>{paid?'Your payment has been authoritatively confirmed by the RideOn server.':'Your booking exists, but payment is not confirmed yet. Check Trips for the latest server status.'}</Text><View style={styles.card}><Text style={styles.kicker}>BOOKING REFERENCE</Text><Text style={styles.reference}>{booking?.bookingId||booking?.id||'—'}</Text><View style={styles.vehicleRow}><View style={styles.vehicleThumb}>{image?<Image source={{uri:image}} style={styles.vehicleImage}/>:<Text style={styles.vehicleEmoji}>{vehicle?.emoji||'🚘'}</Text>}</View><View style={{flex:1,minWidth:0}}><Text style={styles.vehicleName}>{vehicle?.name||booking?.vehicleName||booking?.vehicle?.name||'RideOn vehicle'}</Text>{(vehicle?.type||booking?.vehicle?.type)?<Text style={styles.meta}>{vehicle?.type||booking?.vehicle?.type}</Text>:null}{vendor?<Text style={styles.meta}>Vendor · {vendor}</Text>:null}</View></View>{booking?.status?<Line label="Booking status" value={booking.status}/>:null}{booking?.paymentStatus?<Line label="Payment status" value={booking.paymentStatus}/>:null}{(booking?.startAt||booking?.endAt)&&<Line label="Rental dates" value={[booking?.startAt,booking?.endAt].filter(Boolean).map(v=>new Date(v).toLocaleString('en-IN')).join(' → ')}/>} {pricing.total!=null&&<Line label="Payment" value={money(pricing.total)}/>} {pricing.securityDeposit!=null&&Number(pricing.securityDeposit)>0&&<Line label="Security deposit" value={money(pricing.securityDeposit)+' refundable'}/>}</View><View style={styles.actions}><TouchableOpacity style={styles.primary} onPress={onTrips}><Text style={styles.primaryText}>View My Trips</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={onExplore}><Text style={styles.secondaryText}>Back to Home</Text></TouchableOpacity></View></View>;
}
function Line({label,value}){return <View style={styles.line}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{String(value)}</Text></View>;}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#F6F7F9',padding:24,justifyContent:'center'},icon:{width:74,height:74,borderRadius:37,alignItems:'center',justifyContent:'center',marginBottom:18,alignSelf:'center'},iconSuccess:{backgroundColor:'#E6F6EE'},iconPending:{backgroundColor:'#FFF3E5'},iconText:{fontSize:40,color:C.green,fontWeight:'900'},title:{fontSize:27,fontWeight:'900',color:C.ink,textAlign:'center'},sub:{fontSize:13,color:C.muted,lineHeight:19,textAlign:'center',marginTop:8,marginBottom:18},card:{backgroundColor:C.white,borderRadius:18,borderWidth:1,borderColor:C.line,padding:17},kicker:{fontSize:9,letterSpacing:1.2,fontWeight:'900',color:C.muted},reference:{fontSize:24,fontWeight:'900',color:C.ink,marginTop:5,marginBottom:10},vehicleRow:{flexDirection:'row',alignItems:'center',gap:11,marginBottom:9},vehicleThumb:{width:58,height:48,borderRadius:13,backgroundColor:'#EEF1F5',overflow:'hidden',alignItems:'center',justifyContent:'center'},vehicleImage:{width:'100%',height:'100%',resizeMode:'cover'},vehicleEmoji:{fontSize:25},vehicleName:{fontSize:14,fontWeight:'900',color:C.ink},meta:{fontSize:10,color:C.muted,marginTop:3},line:{flexDirection:'row',justifyContent:'space-between',gap:15,paddingVertical:7,borderTopWidth:1,borderTopColor:'#F0F1F4'},label:{fontSize:11,color:C.muted,flex:1},value:{fontSize:11,fontWeight:'800',color:C.ink,flex:1,textAlign:'right'},actions:{marginTop:17,gap:9},primary:{backgroundColor:C.orange,paddingVertical:15,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,paddingVertical:15,borderRadius:14,alignItems:'center'},secondaryText:{color:C.ink,fontWeight:'900'}});
