import React, { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { rideOnApi } from '../services/api';

const C={ink:'#17202D',muted:'#78818E',orange:'#E85D35',bg:'#F6F7F9',line:'#E8EAF0',white:'#FFFFFF',green:'#16845B'};
const Stars=({value,size=15})=><Text style={{fontSize:size,letterSpacing:1,color:'#F5B940'}}>{[1,2,3,4,5].map(i=><Text key={i} style={{color:i<=Math.round(Number(value)||0)?'#F5B940':'#D7DCE3'}}>★</Text>)}</Text>;

export default function ReviewsSection({vehicleId,vendorId,title='Reviews',compact=false,onWriteReview}) {
  const [data,setData]=useState(null),[vendorData,setVendorData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async()=>{if(!vehicleId&&!vendorId)return;setLoading(true);setError('');try{const [vehicle,vendor]=await Promise.all([vehicleId?rideOnApi.getVehicleReviews(vehicleId,{limit:5}):Promise.resolve(null),vendorId?rideOnApi.getVendorReviews(vendorId,{limit:5}):Promise.resolve(null)]);setData(vehicle);setVendorData(vendor);}catch(e){setError('Reviews are temporarily unavailable. Please try again.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[vehicleId,vendorId]);
  const summary=data?.summary||vendorData?.summary||{averageRating:0,totalReviewCount:0,ratingDistribution:{1:0,2:0,3:0,4:0,5:0}};
  const list=data?.reviews||vendorData?.reviews||[];
  return <View style={[S.card,compact&&S.compact]}>
    <View style={S.head}><View style={{flex:1}}><Text style={S.title}>{title}</Text><Text style={S.sub}>{summary.totalReviewCount?summary.averageRating.toFixed(1)+' average · '+summary.totalReviewCount+' verified review'+(summary.totalReviewCount===1?'':'s'):'No reviews yet'}</Text></View>{summary.totalReviewCount>0&&<View style={S.score}><Text style={S.scoreNum}>{summary.averageRating.toFixed(1)}</Text><Stars value={summary.averageRating} size={12}/></View>}</View>
    {loading?<View style={S.center}><ActivityIndicator color={C.orange}/></View>:error?<View><Text style={S.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={S.link}>Retry</Text></TouchableOpacity></View>:list.length===0?<View style={S.empty}><Text style={S.emptyTitle}>Be the first to share your experience</Text><Text style={S.sub}>Reviews are published after genuine completed rentals.</Text>{onWriteReview&&<TouchableOpacity onPress={onWriteReview} style={S.secondary}><Text style={S.secondaryText}>Write a review</Text></TouchableOpacity>}</View>:<>
      {list.map((review,index)=><View key={review.id||index} style={S.review}><View style={S.row}><View style={S.avatar}><Text style={S.avatarText}>{String(review.reviewerName||'R').slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><View style={S.row}><Text style={S.name}>{review.reviewerName||'RideOn customer'}</Text><Text style={S.date}>{review.createdAt?new Date(review.createdAt).toLocaleDateString():''}</Text></View><Stars value={review.rating}/></View></View>{review.comment?<Text style={S.comment}>{review.comment}</Text>:null}<Text style={S.verified}>✓ Verified completed booking</Text></View>)}
      {onWriteReview&&<TouchableOpacity onPress={onWriteReview} style={S.secondary}><Text style={S.secondaryText}>Write a review</Text></TouchableOpacity>}
    </>}
  </View>;
}
const S=StyleSheet.create({card:{backgroundColor:C.white,borderRadius:20,borderWidth:1,borderColor:C.line,padding:16,marginTop:14},compact:{marginTop:10},head:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:14},title:{fontSize:18,fontWeight:'900',color:C.ink},sub:{fontSize:11,color:C.muted,marginTop:3},score:{alignItems:'flex-end'},scoreNum:{fontSize:22,fontWeight:'900',color:C.ink},center:{padding:18,alignItems:'center'},empty:{backgroundColor:C.bg,borderRadius:14,padding:15},emptyTitle:{fontSize:13,fontWeight:'900',color:C.ink},row:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:34,height:34,borderRadius:17,backgroundColor:'#FFF0E9',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:12,fontWeight:'900',color:C.orange},name:{fontSize:12,fontWeight:'900',color:C.ink},date:{fontSize:10,color:C.muted,marginLeft:'auto'},review:{paddingVertical:14,borderTopWidth:1,borderTopColor:C.line},comment:{fontSize:12,color:'#535D6A',lineHeight:18,marginTop:9},verified:{fontSize:9,fontWeight:'800',color:C.green,marginTop:7},error:{fontSize:11,color:'#A22',lineHeight:17},link:{fontSize:12,fontWeight:'900',color:C.orange,marginTop:6},secondary:{borderWidth:1,borderColor:C.line,borderRadius:13,paddingVertical:12,alignItems:'center',marginTop:10},secondaryText:{fontSize:12,fontWeight:'900',color:C.ink}});
