import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { createPaymentService } from './payments.js';

const response=(payload,status=200)=>({ok:status>=200&&status<300,status,text:async()=>JSON.stringify(payload)});
function fake(routes){const calls=[];const fetchImpl=async(url,options={})=>{calls.push({url,options});const x=routes.find(r=>r.match(url,options));if(!x)throw new Error('Unexpected provider request: '+url);return response(typeof x.body==='function'?x.body():x.body,x.status||200)};return{fetchImpl,calls}}
const service=(o={})=>createPaymentService({provider:'cashfree',clientId:'test-client',clientSecret:'test-secret',webhookSecret:'test-webhook',environment:'sandbox',...o});

test('mock provider is rejected in production',()=>assert.throws(()=>createPaymentService({provider:'mock',environment:'production'}),e=>e.code==='PAYMENT_PROVIDER_CONFIGURATION_REQUIRED'));
test('Cashfree exposes UPI hosted checkout capability',()=>{const s=service();assert.equal(s.configured,true);assert.equal(s.capabilities.provider,'cashfree');assert.equal(s.capabilities.supportsUpi,true);assert.equal(s.capabilities.supportsHostedCheckout,true);assert.equal(s.capabilities.supportsIntent,false);assert.equal(s.capabilities.supportsVpa,false)});
test('Cashfree order creation returns payment session',async()=>{const{fetchImpl,calls}=fake([{match:u=>u.endsWith('/orders/rideon_123'),status:404,body:{}},{match:(u,o)=>u.endsWith('/orders')&&o.method==='POST',body:{order_id:'rideon_123',order_amount:1250,order_currency:'INR',payment_session_id:'session_123'}}]);const r=await service({fetchImpl}).createCustomerPayment({orderId:'rideon_123',amountPaise:125000,customerId:'customer_123',returnUrl:'https://example.com/callback?order_id={order_id}'});assert.equal(r.providerOrderId,'rideon_123');assert.equal(r.paymentSessionId,'session_123');assert.equal(r.amountPaise,125000);assert.equal(JSON.parse(calls[1].options.body).order_amount,1250)});
test('server-side verification rejects amount mismatch',async()=>{const{fetchImpl}=fake([{match:u=>u.endsWith('/orders/o1/payments'),body:[{cf_payment_id:1,order_id:'o1',payment_amount:1249,payment_currency:'INR',payment_status:'SUCCESS'}]}]);const r=await service({fetchImpl}).verifyPayment({providerOrderId:'o1',providerPaymentId:'1',amountPaise:125000});assert.equal(r.verified,false);assert.equal(r.status,'invalid')});
test('server-side verification accepts exact successful payment',async()=>{const{fetchImpl}=fake([{match:u=>u.endsWith('/orders/o1/payments'),body:[{cf_payment_id:2,order_id:'o1',payment_amount:1250,payment_currency:'INR',payment_status:'SUCCESS'}]}]);const r=await service({fetchImpl}).verifyPayment({providerOrderId:'o1',providerPaymentId:'2',amountPaise:125000});assert.equal(r.verified,true);assert.equal(r.status,'paid');assert.equal(r.providerPaymentId,'2')});
test('Cashfree webhook signature uses timestamp plus raw body',()=>{const s=service();const body='{"type":"PAYMENT_SUCCESS_WEBHOOK","data":{}}';const ts='1710000000000';const sig=crypto.createHmac('sha256','test-webhook').update(ts+body).digest('base64');assert.equal(s.verifyWebhook(body,sig,ts),true);assert.equal(s.verifyWebhook(body,sig,'1710000000001'),false)});
test('failed webhook cannot downgrade paid state',()=>{const s=service();assert.equal(s.canTransition('paid','failed'),false);assert.equal(s.canTransition('pending','failed'),true)});
test('refund is idempotent at provider boundary',async()=>{let creates=0;const{fetchImpl}=fake([{match:u=>u.endsWith('/orders/o1/refunds/r1'),status:404,body:{}},{match:(u,o)=>u.endsWith('/orders/o1/refunds')&&o.method==='POST',body:()=>{creates++;return{refund_id:'r1',cf_refund_id:'cf_r1',refund_status:'SUCCESS'}}},{match:u=>u.endsWith('/orders/o1/refunds/r1'),body:{refund_id:'r1',cf_refund_id:'cf_r1',refund_status:'SUCCESS'}}]);const s=service({fetchImpl});const a=await s.refundPayment({providerOrderId:'o1',amountPaise:125000,idempotencyKey:'r1'});const b=await s.refundPayment({providerOrderId:'o1',amountPaise:125000,idempotencyKey:'r1'});assert.equal(a.confirmed,true);assert.equal(b.confirmed,true);assert.equal(creates,1)});
